Repository boostcampwm-2022/web27-Wabinar, pull requests merged in 2022-11, with the labels that each got.

#55 Fix/#50-B: user 초기값이 없을 때 렌더링 되는 문제 해결
  client/src/App.tsx
  client/src/contexts/user.ts
  client/src/pages/Loading/index.tsx
  client/src/pages/Loading/style.module.scss
  client/src/pages/OAuth/index.tsx
  client/src/pages/index.ts
Labels: frontend, fix

#56 Fix/#50-B: userContext 사용
  client/src/components/WorkspaceList/index.tsx
Labels: frontend, fix

#58 Chore/#57-K: API 파라미터 타입 정의
  client/src/apis/auth.ts
  client/src/apis/user.ts
  client/src/components/WorkspaceList/index.tsx
  client/src/pages/OAuth/index.tsx
  client/tsconfig.json
  client/vite.config.ts
  server/apis/auth/controller.ts
  server/apis/auth/service.ts
  server/apis/user/controller.ts
  server/apis/workspace/controller.ts
  server/tsconfig.json
  server/tsconfig.path.json
  types/params/auth.ts
  types/params/user.ts
  types/params/workspace.ts
Labels: chore, API

#68 Refactor/#62-BK: FormModal의 inputValue 상위 컴포넌트로 이동
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/CreateSuccessModal.tsx
  client/src/components/WorkspaceModal/FormModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/components/common/Selector/Dropdown/Menu.tsx
  client/src/components/common/Selector/index.tsx
  client/src/components/index.ts
  client/src/hooks/index.ts
  client/src/types/index.ts
  client/src/types/selector.d.ts
  client/src/types/workspace.d.ts
Labels: frontend, fix

#72 Fix/#69-BK: 초기 접근 URL이 /workspace인 경우 /로 리다이렉트
  client/src/App.tsx
Labels: frontend, fix

#74 Feat/#45-K: 워크스페이스 참여 모달 연동
  client/src/apis/workspace.ts
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/FormModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/components/WorkspaceModal/style.module.scss
  client/src/contexts/set-workspaces.ts
  client/src/hooks/useSetWorkspaces.tsx
Labels: frontend, API

#78 Feat/#75-B: 워크스페이스 설정 모달 UI
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceSetting/SettingModal.tsx
  client/src/components/WorkspaceSetting/index.tsx
  client/src/components/WorkspaceSetting/style.module.scss
  client/src/components/common/Modal/index.tsx
  client/src/components/common/Modal/style.module.scss
  client/src/types/workspace.d.ts
Labels: frontend, UI

#91 Fix/#70-S: 워크스페이스 중복 가입되는 버그 수정
  server/apis/workspace/service.test.ts
  server/apis/workspace/service.ts
Labels: backend, fix

#99 Feat/#98-B: 클립보드 복사 버튼 구현
  client/src/components/common/CopyButton/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#94 Feat/#93-K: 워크스페이스 사이드바 UI
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/SettingIcon.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/style.module.scss
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceSetting/index.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/WorkspaceSettingModal/style.module.scss
  client/src/pages/Workspace/index.tsx
  client/src/pages/Workspace/style.module.scss
  client/src/styles/reset.scss
Labels: 🐥 Frontend, 📱 UIUX

#102 Feat/#82-S : 특정 워크스페이스 멤버, 회의록 API 연동 & 로그인 로직 리팩토링
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/workspace.ts
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/contexts/user.ts
  client/src/pages/OAuth/index.tsx
  client/src/pages/Workspace/index.tsx
  client/src/types/mom.d.ts
  client/src/types/user.d.ts
  client/src/types/workspace.d.ts
  server/apis/auth/controller.ts
  server/apis/user/service.test.ts
  server/apis/user/service.ts
  server/apis/workspace/controller.ts
  server/apis/workspace/service.ts
  server/middlewares/jwt-authenticator.ts
Labels: 🐥 Frontend, 🎒 Backend, 📡 API, 🛠️ Refactor

#103 Chore/#101-K: stylelint 설정과 스크립트 추가
  client/.stylelintrc
  client/package.json
  package-lock.json
  package.json
Labels: 🐥 Frontend, 🧦 Chore, ⚙️ Setting

#105 Feat/#104-S : 회의록 소켓 서버 구축
  client/src/components/Sidebar/SettingIcon.tsx
  client/src/components/Sidebar/style.module.scss
  package-lock.json
  server/apis/mom/model.ts
  server/apis/mom/service.ts
  server/index.ts
  server/package.json
  server/socket/mom.ts
Labels: 🎒 Backend, ✨ Feat

#108 Fix/#107-C: 프록시를 위해 백엔드 api 주소 수정
  server/index.ts
Labels: 🎒 Backend, ⚙️ Setting

#113 Deploy: 회의록 UI & 소켓 서버 & 백엔드 api 수정
  client/.stylelintrc
  client/package.json
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/workspace.ts
  client/src/components/Confbar/index.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/SettingIcon.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/style.module.scss
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceList/style.module.scss
  client/src/components/WorkspaceSetting/index.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/WorkspaceSettingModal/style.module.scss
  client/src/components/common/CopyButton/index.tsx
  client/src/contexts/user.ts
  client/src/pages/OAuth/index.tsx
  client/src/pages/Workspace/index.tsx
  client/src/pages/Workspace/style.module.scss
  client/src/styles/color.module.scss
  client/src/styles/reset.scss
  client/src/types/mom.d.ts
  client/src/types/user.d.ts
  client/src/types/workspace.d.ts
  package-lock.json
  package.json
  server/apis/auth/controller.ts
  server/apis/mom/model.ts
  server/apis/mom/service.ts
  server/apis/user/service.test.ts
  server/apis/user/service.ts
  server/apis/workspace/controller.ts
  server/apis/workspace/service.ts
  server/index.ts
  server/middlewares/jwt-authenticator.ts
  server/package.json
  server/socket/mom.ts
Labels: 🚀 Deploy

#115 Feat/#111-BK: 회의록 CRDT 추가
  client/src/utils/crdt/index.ts
  client/src/utils/crdt/linked-list.ts
  client/src/utils/crdt/node.ts
  client/src/utils/index.ts
Labels: ✨ Feat

#123 Refactor/#118-K: useCRDT로 CRDT 관련 로직 분리
  @wabinar-crdt/index.ts
  client/src/hooks/useCRDT.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#119 Refactor/#118-B: offset 로직 커스텀 훅으로 모듈화
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#125 Refactor/#118-BK: 에디터 컴포넌트 리팩토링
  client/src/components/Editor/index.tsx
  client/src/config/index.ts
  client/src/hooks/useCRDT.tsx
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#127 Feat/temp-C : WebRTC 시그널링 구현
  client/package.json
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/ConfMedia/style.module.scss
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/ConfMediaBar/style.module.scss
  client/src/constants/rtc.ts
  client/src/hooks/useConfMediaStreams.tsx
  client/src/main.tsx
  client/src/pages/Workspace/index.tsx
  client/src/utils/rtc/index.ts
  package-lock.json
  server/apis/auth/service.github.ts
  server/index.ts
  server/socket/index.ts
  server/socket/signaling.ts
  server/tsconfig.path.json
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#117 Feat/#116-BK: 에디터 공동 편집 블럭
  @wabinar-crdt/index.ts
  @wabinar-crdt/linked-list.ts
  @wabinar-crdt/node.ts
  @wabinar-crdt/package.json
  client/src/components/Editor/index.tsx
  client/src/components/Editor/style.module.scss
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/hooks/useCRDT.tsx
  client/src/hooks/useOffset.tsx
  client/src/main.tsx
  package-lock.json
  server/package.json
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#133 Refactor/#129-K: ConfMediaBar 컴포넌트 관련 리팩토링
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/Confbar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/hooks/useConfMediaStreams.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#131 Feat/#126-BK: 회의록 DB에 저장하기
  @wabinar-crdt/index.ts
  @wabinar-crdt/linked-list.ts
  client/src/components/Editor/index.tsx
  client/src/hooks/useCRDT.tsx
  server/apis/mom/model.ts
  server/apis/mom/service.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#135 Feat/#132-K: CRDT 패키지 개선
  @wabinar-crdt/convergence.test.ts
  @wabinar-crdt/crdt.test.ts
  @wabinar-crdt/index.ts
  @wabinar-crdt/jest.config.js
  @wabinar-crdt/linked-list.ts
  @wabinar-crdt/node.ts
  @wabinar-crdt/package.json
  @wabinar-crdt/tsconfig.json
  client/src/hooks/useCRDT.tsx
  package-lock.json
Labels: ✨ Feat, 🛠️ Refactor

#141 Feat/#140-B: QuestionBlock 구현
  client/src/components/QuestionBlock/index.tsx
  client/src/components/QuestionBlock/style.module.scss
Labels: 🐥 Frontend, 📱 UIUX, ✨ Feat

#149 Feat/#145-S : 마이크/캠 on/off 기능
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/StreamButton/CamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/MicButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/style.module.scss
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/ConfMediaBar/style.module.scss
  client/src/components/Confbar/index.tsx
  client/src/styles/color.module.scss
Labels: 🐥 Frontend, ✨ Feat

#144 Feat/#139-S : 회의 시작/종료 소켓 이벤트 구현
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/StreamButton/CamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/MicButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/style.module.scss
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/ConfMediaBar/style.module.scss
  client/src/components/Confbar/index.tsx
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/contexts/conf.ts
  client/src/contexts/set-workspaces.ts
  client/src/contexts/workspaces.ts
  client/src/hooks/useConfContext.ts
  client/src/hooks/useWorkspaceContext.ts
  client/src/pages/Workspace/index.tsx
  client/src/styles/color.module.scss
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#148 Feat/#140-B: VoteBlock UI 구현
  client/src/components/VoteBlock/index.tsx
  client/src/components/VoteBlock/style.module.scss
Labels: 🐥 Frontend, 📱 UIUX, ✨ Feat

#143 Refactor/#142-S : 소켓 Context 생성
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/StreamButton/CamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/MicButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/index.tsx
  client/src/components/ConfMediaBar/StreamButton/style.module.scss
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/ConfMediaBar/style.module.scss
  client/src/components/Confbar/index.tsx
  client/src/components/Editor/index.tsx
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/contexts/conf.ts
  client/src/contexts/set-workspaces.ts
  client/src/contexts/socket.ts
  client/src/contexts/workspaces.ts
  client/src/hooks/useConfContext.ts
  client/src/hooks/useSocket.ts
  client/src/hooks/useSocketContext.ts
  client/src/hooks/useWorkspaceContext.ts
  client/src/pages/Workspace/index.tsx
  client/src/styles/color.module.scss
  server/socket/mom.ts
Labels: 🐥 Frontend, 🛠️ Refactor

#150 Feat/#146-K: DB 저장을 위해 CRDT 링크드리스트의 중첩 제거
  @wabinar-crdt/convergence.test.ts
  @wabinar-crdt/index.ts
  @wabinar-crdt/linked-list.ts
  @wabinar-crdt/node.ts
Labels: ✨ Feat

#158 Feat/#157-K: 사이드바 기능 연동
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/types/mom.d.ts
  server/apis/workspace/service.test.ts
  server/apis/workspace/service.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#163 Feat/#159-B: 선택된 회의록 Context 생성 & 적용
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/contexts/selected-mom.ts
  client/src/hooks/useSelectedMom.ts
  client/src/types/mom.d.ts
Labels: 🐥 Frontend, ✨ Feat

#170 Feat/#165-B: 워크스페이스 변경
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceThumbnailList/WorkspaceThumbnailItem.tsx
  client/src/components/WorkspaceThumbnailList/index.tsx
  server/apis/mom/model.ts
  server/apis/mom/service.ts
  server/apis/workspace/model.ts
  server/apis/workspace/service.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 📡 API, ✨ Feat

#171 Feat/#167-S : 투표 종료 소켓 이벤트 작성
  server/apis/mom/vote/service.ts
  server/socket/mom.ts
Labels: 🎒 Backend, ✨ Feat

#166 Feat/#160-S : 투표 생성, 수정 API 작성
  server/apis/mom/vote/service.ts
  server/socket/mom.ts
Labels: 🎒 Backend, ✨ Feat
