Repository boostcampwm-2022/web27-Wabinar, pull requests merged in 2022-12, with the labels that each got.

#169 Feat/#168-C: 질문 추가 및 해결 토글 소켓 이벤트 핸들링
  client/src/components/QuestionBlock/index.tsx
  server/apis/mom/questions/service.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, 📡 API

#176 Fix/#175-S: 소켓 커넥션이 여러번 생성되는 이슈 해결
  client/src/components/ConfMediaBar/index.tsx
  client/src/contexts/socket.ts
  client/src/pages/Workspace/index.tsx
Labels: 🐞 Fix

#185 Fix/#161-K: CRDT 버그 수정
  client/src/components/Mom/index.tsx
  package-lock.json
  server/apis/mom/service.ts
  server/socket/mom.ts
Labels: 🎒 Backend, 🐞 Fix

#174 Feat/#161-K: 회의록 에디터에서 블럭 여러개 사용
  @wabinar-crdt/convergence.test.ts
  @wabinar-crdt/crdt.test.ts
  @wabinar-crdt/index.ts
  @wabinar-crdt/linked-list.ts
  client/package.json
  client/src/components/Editor/style.module.scss
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/EventEmitter.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/components/Workspace/index.tsx
  client/src/hooks/useCRDT.tsx
  package-lock.json
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/service.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, ✨ Feat

#187 Fix/#186-C: 본인 목소리 안 들리도록 개선
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/index.tsx
Labels: 🐥 Frontend, 🐞 Fix

#180 Refactor/#178-C: 환경 변수로 분리
  server/config/index.ts
  server/index.ts
Labels: 🛠️ Refactor

#184 Refactor/#182-B: 회의록 선택시 불필요한 리렌더링 방지
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/Sidebar/Header.tsx
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/hooks/useSelectedMom.ts
Labels: 🐥 Frontend, 🛠️ Refactor

#188 Deploy: 4주차 결과
  @wabinar-crdt/convergence.test.ts
  @wabinar-crdt/crdt.test.ts
  @wabinar-crdt/index.ts
  @wabinar-crdt/linked-list.ts
  README.md
  client/package.json
  client/src/components/ConfMediaBar/ConfMedia/index.tsx
  client/src/components/ConfMediaBar/index.tsx
  client/src/components/Editor/style.module.scss
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/EventEmitter.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/components/QuestionBlock/index.tsx
  client/src/components/Sidebar/ConfButton.tsx
  client/src/components/Sidebar/Header.tsx
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/WorkspaceThumbnailList/WorkspaceThumbnailItem.tsx
  client/src/components/WorkspaceThumbnailList/index.tsx
  client/src/constants/socket-message.ts
  client/src/contexts/selected-mom.ts
  client/src/contexts/socket.ts
  client/src/hooks/useCRDT.tsx
  client/src/hooks/useSelectedMom.ts
  client/src/pages/Workspace/index.tsx
  client/src/types/mom.d.ts
  client/src/utils/rtc/index.ts
  package-lock.json
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/model.ts
  server/apis/mom/questions/service.ts
  server/apis/mom/service.ts
  server/apis/mom/vote/service.ts
  server/apis/user/controller.ts
  server/apis/workspace/model.ts
  server/apis/workspace/service.test.ts
  server/apis/workspace/service.ts
  server/config/index.ts
  server/constants/socket-message.ts
  server/index.ts
  server/middlewares/error-handler.ts
  server/socket/mom.ts
  server/socket/signaling.ts
Labels: 🚀 Deploy

#195 Refactor/#194-K: 회의록 소켓 서버 리팩토링
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/index.tsx
  server/apis/mom/block/service.ts
  server/socket/mom.ts
  server/utils/crdt-manager.ts
Labels: 🎒 Backend, 🐞 Fix, 🛠️ Refactor

#196 Refactor/#194-K: 회의록 소켓 이벤트 상수화
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/constants/socket-message.ts
  server/constants/socket-message.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, 🛠️ Refactor

#198 Feat/#197-K: 회의록 제목 수정 기능
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/constants/socket-message.ts
  client/src/hooks/useDebounce.ts
  client/src/types/mom.d.ts
  server/apis/mom/model.ts
  server/apis/mom/service.ts
  server/apis/workspace/service.ts
  server/constants/socket-message.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#207 Feat/#200-B: 가입한 워크스페이스 없을 때 페이지
  client/src/components/Workspace/DefaultWorkspace.tsx
  client/src/components/Workspace/style.module.scss
  client/src/components/common/GuideIcon/GuideMessage.tsx
  client/src/components/common/GuideIcon/index.tsx
  client/src/components/common/GuideIcon/style.module.scss
  client/src/components/common/Icon/Wab/AmazedWabIcon.tsx
  client/src/components/common/Icon/Wab/SleepingWabIcon.tsx
  client/src/components/common/Icon/Wab/index.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🐥 Frontend, 📱 UIUX, ✨ Feat

#211 Refactor/#205-K: 가입된 워크스페이스 정보 Context 통일
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/user.ts
  client/src/components/Sidebar/MemberList.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/contexts/user.ts
  client/src/contexts/workspaces.ts
  client/src/hooks/useCRDT.tsx
  client/src/hooks/useWorkspacesContext.ts
  client/src/pages/OAuth/index.tsx
  client/src/pages/Workspace/index.tsx
  client/src/types/user.d.ts
  client/src/types/workspace.d.ts
  types/params/user.ts
  types/params/workspace.ts
Labels: 🐥 Frontend, 🛠️ Refactor

#215 Hotfix: momSocketServer 잘못된 namespace 수정
  server/socket/mom.ts
Labels: 🎒 Backend, 🔥 Hotfix

#214 Hotfix: momSocketServer 잘못된 namespace 수정
  server/socket/mom.ts
  server/tsconfig.path.json
Labels: 🎒 Backend, 🔥 Hotfix

#224 Fix/#222-B: 회의록 변경 시 소켓 이벤트가 안오는 이슈 해결
  client/src/components/Mom/index.tsx
Labels: 🐥 Frontend, 🐞 Fix

#227 Chore/#223-C: CI에서 백엔드 코드가 실행되는지 테스트
  .github/workflows/ci.yml
  server/tsconfig.path.json
Labels: 🧦 Chore

#228 Fix/#226-K: 블럭 내부 좌우 방향키 커서 핸들러 개선
  client/src/components/Mom/Block/index.tsx
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🐞 Fix

#217 Feat/#216-K: 워크스페이스 생성 시 해당 워크스페이스로 이동
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/CreateSuccessModal.tsx
  client/src/components/WorkspaceModal/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#233 Feat/#221-B: 회의록 붙여넣기 기능 구현
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/constants/socket-message.ts
  server/constants/socket-message.ts
  server/socket/mom.ts
Labels: 🐥 Frontend, ✨ Feat

#240 Refactor/#239-B: 한글 입력 소켓 메시지 적용
  client/src/components/Mom/Block/index.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#225 Feat/#219-S : 블록 선택할 수 있는 UI 구현
  client/src/components/BlockSelector/BlockItem/index.tsx
  client/src/components/BlockSelector/BlockItem/style.module.scss
  client/src/components/BlockSelector/index.tsx
  client/src/components/BlockSelector/style.module.scss
  client/src/components/Workspace/index.tsx
  client/src/constants/block.ts
Labels: 🐥 Frontend, ✨ Feat

#218 Feat/#213-B: 워크스페이스 생성 완료 모달에 CopyButton 적용
  client/src/components/WorkspaceModal/FormModal.tsx
  client/src/components/WorkspaceModal/style.module.scss
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/WorkspaceSettingModal/style.module.scss
  server/apis/user/service.ts
Labels: 🐥 Frontend, ✨ Feat

#250 Fix/#243-C: 워크스페이스 이동 시 기존 소켓 연결 해제
  client/src/components/Workspace/index.tsx
  server/debug/websocket-analyzer.ts
Labels: 🐥 Frontend, 🎒 Backend, 🐞 Fix

#253 Fix/#220-C: 워크스페이스 변경시에도 화상회의가 지속되는 버그 해결
  client/src/components/Workspace/index.tsx
Labels: 🐥 Frontend, 🐞 Fix

#256 Feat/#252-BK: 블럭 첫번째 오프셋에서 / 입력을 통해 타입 선택
  @wabinar/api-types/block.ts
  client/src/components/BlockSelector/BlockItem/index.tsx
  client/src/components/BlockSelector/index.tsx
  client/src/components/BlockSelector/style.module.scss
  client/src/components/Mom/Block/TextBlock.tsx
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/constants/block.ts
  client/src/constants/socket-message.ts
  package-lock.json
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/constants/socket-message.ts
  server/socket/mom.ts
  server/utils/crdt-manager.ts
Labels: 🐥 Frontend, 🎒 Backend, 📡 API, ✨ Feat

#235 Feat/#199-K: 블럭 추가/삭제에 포커스와 커서 이동
  client/src/components/Mom/Block/TextBlock.tsx
  client/src/components/Mom/Block/index.tsx
  client/src/components/Mom/index.tsx
  server/socket/mom.ts
Labels: 🐥 Frontend, ✨ Feat

#258 Chore/#247-K: 서버 디렉토리 vite로 빌드 및 배포 스크립트 수정
  @wabinar/api-types/tsconfig.json
  @wabinar/crdt/tsconfig.json
  client/package.json
  deploy-scripts/build-backend.sh
  deploy-scripts/build-frontend-and-backend.sh
  deploy-scripts/build-frontend.sh
  deploy-scripts/pre-build.sh
  deploy-scripts/pull-production-dotenv.sh
  deploy-scripts/try-dotenv-vault-login.sh
  deploy.sh
  package-lock.json
  package.json
  server/package.json
  server/tsconfig.json
  server/tsconfig.path.json
  server/vite.config.ts
Labels: 🎒 Backend, 🧦 Chore, ⚙️ Setting

#269 Fix/#266-B: 누락된 setIsOpen로직 추가
  client/src/components/Mom/Block/TextBlock.tsx
Labels: 🐥 Frontend, 🐞 Fix

#267 Chore/#265-C: 백엔드 빌드 디렉토리에 환경변수 파일 복사
  deploy-scripts/build-frontend-and-backend.sh
Labels: 🎒 Backend, ⚙️ Setting

#286 Refactor/#283-B: isStart 네이밍 isOnGoing으로 변경
  client/src/components/Sidebar/MeetingButton.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/contexts/meeting.ts
Labels: 🛠️ Refactor

#278 Refactor/#276-B: conf 네이밍 모두 Meeting으로 변경 및 적용
  client/src/components/MeetingMediaBar/MeetingMedia/index.tsx
  client/src/components/MeetingMediaBar/MeetingMedia/style.module.scss
  client/src/components/MeetingMediaBar/StreamButton/CamButton/index.tsx
  client/src/components/MeetingMediaBar/StreamButton/MicButton/index.tsx
  client/src/components/MeetingMediaBar/StreamButton/index.tsx
  client/src/components/MeetingMediaBar/StreamButton/style.module.scss
  client/src/components/MeetingMediaBar/index.tsx
  client/src/components/MeetingMediaBar/style.module.scss
  client/src/components/Sidebar/MeetingButton.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/style.module.scss
  client/src/components/Workspace/index.tsx
  client/src/contexts/conf.ts
  client/src/contexts/meeting.ts
  client/src/hooks/useMeetingContext.ts
  client/src/hooks/useMeetingMediaStreams.tsx
Labels: 🐥 Frontend, 🛠️ Refactor

#279 Refactor/#275-C: RTC 모듈 메소드 관심사 분리
  client/src/utils/rtc/index.ts
Labels: 🛠️ Refactor

#264 Chore/#261-C: 프로젝트 절대경로 알아내도록 변경
  deploy-scripts/config.sh
  deploy.sh
Labels: ⚙️ Setting

#273 Refactor/#270-B: 에러 메세지 상수화 및 적용
  client/src/components/WorkspaceModal/CreateSuccessModal.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/constants/error-message.ts
  client/src/hooks/useCRDT.tsx
  client/src/hooks/useMeetingContext.ts
  client/src/hooks/useSelectedMom.ts
  client/src/hooks/useSocketContext.ts
  client/src/hooks/useUserContext.tsx
  client/src/hooks/useWorkspacesContext.ts
  server/apis/auth/service.github.ts
  server/apis/workspace/service.ts
  server/constants/error-message.ts
Labels: 🐥 Frontend, 🎒 Backend, 🛠️ Refactor

#281 Chore/#280-K: lint-staged에 prettier --write 추가
  package.json
Labels: 🧦 Chore, ⚙️ Setting

#277 Style/#271-K: CSS 개선 작업
  client/src/components/MeetingMediaBar/style.module.scss
  client/src/components/Mom/DefaultMom.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/SettingIcon.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/style.module.scss
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceList/style.module.scss
  client/src/components/common/Button/style.module.scss
  client/src/components/common/Icon/Wabinar/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.module.scss
Labels: 🐥 Frontend, 📱 UIUX, 🛠️ Refactor

#288 Refactor/#287-S : 소켓 상태 관리 리팩토링 - 다른 워크스페이스 접속 시 이전 연결 끊기 리팩토링
  client/src/components/Workspace/index.tsx
  client/src/hooks/useSocket.ts
Labels: 🐥 Frontend, 🛠️ Refactor

#292 Feat/#289-S : 투표 결과 UI에 보여주기
  client/src/components/common/Templates/VoteBlock/index.tsx
  client/src/components/common/Templates/VoteBlock/style.module.scss
Labels: 🐥 Frontend, ✨ Feat

#309 Refactor/#301-B: useOffset 훅, Mom, Block 컴포넌트 핸들러 네이밍 구체화
  client/src/components/Block/TextBlock.tsx
  client/src/components/Mom/index.tsx
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🧦 Chore, 🛠️ Refactor

#307 Feat/#300-K: 투표 블럭을 생성한 사람만 등록 가능하도록 수정
  @wabinar/constants/socket-message.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/VoteBlock/VoteBlockTemplate.tsx
  client/src/components/Block/VoteBlock/index.tsx
  client/src/components/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/constants/block.ts
  server/socket/Mom/handleTextBlock.ts
  server/socket/Mom/handleVoteBlock.ts
Labels: 🐥 Frontend, ✨ Feat

#316 Fix/#315-B: Windows에서 cache 패스
  .github/workflows/ci.yml
Labels: 🐞 Fix

#302 Feat/#301-B: onBlur 핸들러에 모달 안보이게 하는 로직 추가
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, ✨ Feat

#308 Fix/#303-B: 블록 추가시 포커스 잡히지 않는 버그 해결
  client/src/components/Block/TextBlock.tsx
  client/src/components/Mom/index.tsx
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🐞 Fix

#314 Style/#271-K: CSS 개선 작업
  client/src/components/BlockSelector/style.module.scss
  client/src/pages/Workspace/style.module.scss
Labels: 🐥 Frontend, 📱 UIUX

#304 Feat/#300-K: 투표 블럭 서비스 로직 연동
  @wabinar/constants/socket-message.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/VoteBlock/VoteBlockTemplate.tsx
  client/src/components/Block/VoteBlock/index.tsx
  client/src/components/Block/VoteBlock/style.module.scss
  client/src/components/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/constants/block.ts
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/block/vote/service.ts
  server/apis/mom/vote/service.ts
  server/socket/Mom/handleTextBlock.ts
  server/socket/Mom/handleVoteBlock.ts
Labels: 🐥 Frontend, 🎒 Backend, ✨ Feat

#318 Fix/#317-K: 회의록 createdAt 고정값으로 들어가는 이슈
  server/apis/mom/model.ts
Labels: 🎒 Backend, 🐞 Fix

#294 Feat/#293-C: 스트림 외에 캠/마이크 상태를 제공하도록 변경
  client/src/hooks/useMeetingMediaStreams.tsx
  client/src/hooks/useMeetingMediaStreamsV2.tsx
Labels: 🐥 Frontend, ✨ Feat

#324 Style/#271-B: h 태그, 텍스트 스타일 수정
  client/src/components/Mom/style.module.scss
Labels: 🐥 Frontend, 📱 UIUX

#322 Fix/#321-K: 블럭 타입 선택 모달 닫는 기능에 dimmer 활용
  client/src/components/Block/TextBlock.tsx
  client/src/components/BlockSelector/index.tsx
  client/src/components/BlockSelector/style.module.scss
  client/src/hooks/useOffset.tsx
Labels: 🐥 Frontend, 🐞 Fix

#323 Feat/#319-K: 블럭 타입 변경 이후 입력된 / 제거
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#320 Deploy: 5주차 주말 작업 배포
  .github/workflows/ci.yml
  @wabinar/constants/socket-message.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/VoteBlock/VoteBlockTemplate.tsx
  client/src/components/Block/VoteBlock/index.tsx
  client/src/components/Block/VoteBlock/style.module.scss
  client/src/components/Block/index.tsx
  client/src/components/BlockSelector/index.tsx
  client/src/components/BlockSelector/style.module.scss
  client/src/components/Mom/index.tsx
  client/src/components/Mom/style.module.scss
  client/src/constants/block.ts
  client/src/hooks/useMeetingMediaStreams.tsx
  client/src/hooks/useMeetingMediaStreamsV2.tsx
  client/src/hooks/useOffset.tsx
  client/src/pages/Workspace/style.module.scss
  client/vite.config.ts
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/block/vote/service.ts
  server/apis/mom/model.ts
  server/apis/mom/vote/service.ts
  server/socket/Mom/handleTextBlock.ts
  server/socket/Mom/handleVoteBlock.ts
Labels: 🚀 Deploy

#330 Chore/#329-K: 공통 패키지 폴더 정리
  @wabinar/api-types/auth.ts
  @wabinar/api-types/workspace.ts
  @wabinar/constants/block.ts
  @wabinar/constants/package.json
  client/src/apis/auth.ts
  client/src/apis/workspace.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/BlockSelector/BlockItem/index.tsx
  client/src/components/BlockSelector/index.tsx
  package-lock.json
  server/apis/auth/controller.ts
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/block/vote/service.ts
  server/apis/workspace/controller.ts
  server/socket/Mom/handleQuestionBlock.ts
  server/utils/crdt-manager.ts
Labels: 🧦 Chore

#331 Docs: 테스트 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/test.md
Labels: ⚙️ Setting

#328 Feat/#327-K: CRDT 에러 핸들러 추가
  @wabinar/crdt/linked-list.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/Mom/index.tsx
  client/src/hooks/useCRDT.tsx
Labels: 🐥 Frontend, ✨ Feat

#335 Feat/#295-C: 캠/마이크 상태 전달을 위한 소켓 이벤트 핸들링
  server/socket/workspace.ts
Labels: 🎒 Backend, ✨ Feat

#336 Feat/#254-C: 피어가 캠/마이크 조작 시 아이콘 변경
  client/src/components/MeetingMediaBar/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#354 Perf/#352-B: font 불러오는 시간 개선 (FCP)
  client/index.html
  client/src/styles/reset.scss
Labels: 🐥 Frontend

#351 Refactor/#350-S : Context hook 디렉토리 구분
  client/src/components/Block/QuestionBlock/index.tsx
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/VoteBlock/VoteBlockTemplate.tsx
  client/src/components/Block/VoteBlock/index.tsx
  client/src/components/Block/index.tsx
  client/src/components/MeetingMediaBar/index.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MeetingButton.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/common/Selector/Dropdown/Item.tsx
  client/src/components/common/Selector/Dropdown/Menu.tsx
  client/src/components/common/Selector/Dropdown/Trigger.tsx
  client/src/hooks/context/useDropdownContext.ts
  client/src/hooks/context/useMeetingContext.ts
  client/src/hooks/context/useSelectedMomContext.ts
  client/src/hooks/context/useSocketContext.ts
  client/src/hooks/context/useUserContext.ts
  client/src/hooks/context/useWorkspacesContext.ts
  client/src/hooks/useCRDT.ts
  client/src/hooks/useMeetingMediaStreams.ts
  client/src/hooks/useMeetingMediaStreamsV2.ts
  client/src/hooks/useOffset.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🧦 Chore, 🛠️ Refactor

#346 Refactor/#338-K: 초기 접속 시 페이지 이동 UX 개선
  client/src/App.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🐥 Frontend, ✨ Feat, 🛠️ Refactor

#334 Deploy: 6주차 중간 배포
  .github/ISSUE_TEMPLATE/test.md
  .github/workflows/ci.yml
  @wabinar/api-types/auth.ts
  @wabinar/api-types/workspace.ts
  @wabinar/constants/block.ts
  @wabinar/constants/package.json
  @wabinar/crdt/linked-list.ts
  client/index.html
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/workspace.ts
  client/src/components/Block/QuestionBlock/index.tsx
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/VoteBlock/VoteBlockTemplate.tsx
  client/src/components/Block/VoteBlock/index.tsx
  client/src/components/Block/index.tsx
  client/src/components/BlockSelector/BlockItem/index.tsx
  client/src/components/BlockSelector/index.tsx
  client/src/components/MeetingMediaBar/index.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MeetingButton.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Workspace/index.tsx
  client/src/components/WorkspaceList/index.tsx
  client/src/components/WorkspaceModal/CreateModal.tsx
  client/src/components/WorkspaceModal/JoinModal.tsx
  client/src/components/WorkspaceSettingModal/index.tsx
  client/src/components/common/Selector/Dropdown/Item.tsx
  client/src/components/common/Selector/Dropdown/Menu.tsx
  client/src/components/common/Selector/Dropdown/Trigger.tsx
  client/src/hooks/context/useDropdownContext.ts
  client/src/hooks/context/useMeetingContext.ts
  client/src/hooks/context/useSelectedMomContext.ts
  client/src/hooks/context/useSocketContext.ts
  client/src/hooks/context/useUserContext.ts
  client/src/hooks/context/useWorkspacesContext.ts
  client/src/hooks/useCRDT.ts
  client/src/hooks/useMeetingMediaStreams.ts
  client/src/hooks/useMeetingMediaStreamsV2.ts
  client/src/hooks/useOffset.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Workspace/index.tsx
  client/src/styles/reset.scss
  package-lock.json
  server/apis/auth/controller.ts
  server/apis/mom/block/model.ts
  server/apis/mom/block/service.ts
  server/apis/mom/block/vote/service.ts
  server/apis/workspace/controller.ts
  server/socket/Mom/handleQuestionBlock.ts
  server/socket/workspace.ts
  server/utils/crdt-manager.ts
Labels: 🚀 Deploy

#362 Test/C: CRDT 테스트 케이스 수정 및 예외 케이스 추가
  @wabinar/crdt/linked-list.ts
  @wabinar/crdt/test/crdt.test.ts
Labels: 🔎 Test

#337 Test/#333-K: CRDT 테스트 케이스 추가
  @wabinar/crdt/convergence.test.ts
  @wabinar/crdt/crdt.test.ts
  @wabinar/crdt/linked-list.ts
  @wabinar/crdt/test/convergence.test.ts
  @wabinar/crdt/test/crdt.test.ts
  @wabinar/crdt/test/exception.test.ts
  @wabinar/crdt/test/utils.ts
  @wabinar/crdt/tsconfig.json
Labels: 🔎 Test

#363 Chore/#280-K: lint-staged 스크립트에 @wabinar 디렉토리 파일 추가
  package.json
Labels: 🧦 Chore

#364 Fix/#361-B: init 후에도 Caret이 유지되게 해결
  client/src/components/Block/TextBlock.tsx
  client/src/hooks/useOffset.ts
Labels: 🐥 Frontend, 🐞 Fix

#373 Feat/#372-K: 회의록 제목 변경 MomList에 반영
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Sidebar/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#378 Chore/#377-C: 테스트 커버리지 출력
  .gitignore
  @wabinar/crdt/jest.config.js
  server/jest.config.js
Labels: ⚙️ Setting

#310 Docs: README 작성
  README.md
Labels: 🧦 Chore

#384 Chore/#377-C: CI에 CRDT 패키지 테스트
  .github/workflows/ci.yml
Labels: ⚙️ Setting

#376 Fix/#375-K: 회의록 블럭 memo 조건 추가
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/index.tsx
Labels: 🐥 Frontend, ✨ Feat

#382 Test/#381-C: trackSetter 모듈 테스트
  client/jest.config.js
  client/package.json
  client/src/utils/trackSetter/index.test.ts
  client/src/utils/trackSetter/index.ts
Labels: 🔎 Test, 🛠️ Refactor

#387 Refactor/#386-C: 긴 메소드의 코드를 여러 private 메소드로 분리
  client/src/utils/rtc/index.ts
Labels: 🐥 Frontend, 🛠️ Refactor

#389 Perf/#388-B: MomList isMemoized 함수 추가
  client/src/components/Sidebar/MomList.tsx
Labels: 🐥 Frontend, 🤹Perf

#385 Fix/#383-B: 처음 입장 시 Default MOM이 깜빡거리는 현상 해결
  @wabinar/constants/socket-message.ts
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
Labels: 🐥 Frontend, 🐞 Fix

#374 Perf/#368-S : SEO 를 위한 meta 태그 추가
  client/index.html
  client/package.json
  client/src/App.tsx
  client/src/components/MetaHelmet/index.tsx
  client/src/constants/meta.ts
  client/src/main.tsx
  client/vite.config.ts
  package-lock.json
Labels: 🐥 Frontend, 🤹Perf

#391 Feat/#380-S : React.lazy + Suspense 적용
  client/src/App.tsx
  client/src/components/Mom/Skeleton.tsx
  client/src/components/Sidebar/Skeleton.tsx
  client/src/components/Sidebar/style.module.scss
  client/src/components/Workspace/Skeleton/index.tsx
  client/src/components/Workspace/Skeleton/style.module.scss
  client/src/components/WorkspaceList/Skeleton.tsx
  client/src/components/common/Icon/Bubbles/index.tsx
  client/src/components/common/Icon/Logo/index.tsx
  client/src/pages/Workspace/index.tsx
  client/src/pages/index.ts
  server/apis/user/controller.ts
  server/apis/workspace/controller.ts
Labels: 🐥 Frontend

#397 Feat/#396-K: 회의록 및 텍스트 블럭 관련 소켓 메세지 인터페이스 정의
  @wabinar/api-types/block.ts
  @wabinar/api-types/mom.ts
  client/src/components/Block/TextBlock.tsx
  client/src/components/Block/index.tsx
  client/src/components/Mom/index.tsx
  client/src/components/Sidebar/MomList.tsx
  client/src/components/Workspace/index.tsx
  client/src/hooks/useCRDT.ts
  server/socket/Mom/handleTextBlock.ts
  server/socket/Mom/index.ts
  server/socket/index.ts
  server/socket/mom/handleQuestionBlock.ts
  server/socket/mom/handleTextBlock.ts
  server/socket/mom/handleVoteBlock.ts
  server/socket/mom/index.ts
Labels: 📡 API, ✨ Feat

#345 Feat/#339-S : RTC hook 버전 구현
  @wabinar/constants/socket-message.ts
  client/src/constants/rtc.ts
  client/src/contexts/rtc.ts
  client/src/hooks/context/useMyMediaStreamContext.ts
  client/src/hooks/context/useUserStreamsContext.ts
  client/src/hooks/useCreateMediaStream.ts
  client/src/hooks/useJoinMeeting.ts
  client/src/hooks/usePeerConnection.ts
Labels: 🐥 Frontend, ✨ Feat

#401 Feat/#400-C: 배포 서버 백엔드에서 자세한 정보 로깅
  server/config/index.ts
  server/index.ts
Labels: 🎒 Backend

#402 hotfix: App, WorkspacePage에 isLoaded 상태 추가
  client/src/App.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🐞 Fix

#403 hotfix: App, WorkspacePage에 isLoaded 상태 추가
  client/src/App.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🐞 Fix

#404 hotfix: blockRef 가드 추가
  client/src/components/Block/TextBlock.tsx
Labels: 🐞 Fix

#405 hotfix: blockRef 가드 추가
  client/src/components/Block/TextBlock.tsx
Labels: 🐞 Fix

#407 Hotfix: 6주차 배포 추가 수정
  client/src/components/Mom/index.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🔥 Hotfix

#406 Hotfix: 6주차 배포 추가 수정
  client/src/components/Mom/index.tsx
  client/src/pages/Workspace/index.tsx
Labels: 🔥 Hotfix

#408 Hotfix-S : SEO 작업 html 파일에 임시로 넣어두기
  client/index.html
  client/public/og-img.png
  client/src/App.tsx
  client/src/main.tsx
Labels: 🔥 Hotfix
